config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]

  match 'add_nested_fields' => 'nested_form#add_nested_fields', via: :get
  root 'application#index'
  resources :customers
  resources :prestations
  resources :tvas
  resources :guaranties
  resources :estimations do 
    member do
      get 'generate_pdf'
      get 'send_pdf'
    end
  end

end

app/models/estimation.rb
class Estimation < ActiveRecord::Base
	belongs_to :customer, required: true
	belongs_to :guaranty, required: true
	has_many :volets, dependent: :destroy
	accepts_nested_attributes_for :volets, allow_destroy: true

	scope :with_associations, -> (*){ eager_load(:customer, :guaranty, volets: {prestation_lines: {prestation: :tva}}) }
	#
	# validation
	#
	validates :libelle, :objet, :reference, :intervention_dates, :validity_date, presence: :true


	def generate_pdf
		# Initialisation
		pdf = Prawn::Document.new(page_size: 'A4')
		
		full_sanitizer = Rails::Html::WhiteListSanitizer.new
		permit_tags = %w(b i u strikethrough sub sup font color link)
		permit_attributes = %w(color)

		title_color = "0000FF"
		section_color = "00FF80"

		recap = []
		estimation_total_ht, estimation_total_ttc = 0
		estimation_tva = {}
		Tva.all.each{|t| estimation_tva[t.id] = 0}

		# Affichage Adresse
		pdf.move_down 100
		pdf.bounding_box([200, pdf.cursor], width: 300, height: 150) do
			pdf.text "CHAMPFLEURY, le 5 Novembre 2015" ### AJOUTER DATE DEVIS ET PRENDRE CE CHAMP : self.date	
			pdf.move_down 10
			if self.customer
				pdf.text (self.customer.first_name + ' ' + self.customer.last_name)
				adress = self.customer.adresses.first
				if adress
					pdf.text adress.rue # AJOUTER ADRESSE CHOISI DANS DEVIS self.adresse_client
					pdf.text adress.complement if  adress.complement # AJOUTER ADRESSE CHOISI DANS DEVIS self.adresse_client
					pdf.text (adress.code_postal + ' - ' + adress.ville)
				end
			end

			pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
		end

		# Affichage OBJET
		pdf.move_down 100
		pdf.bounding_box([150, pdf.cursor], width: 350, height: 500) do
			pdf.text "N/REF. : #{self.reference}"
			pdf.text "OBJET : #{self.objet}"
			pdf.move_down 30
			pdf.text "Madame, Monsieur,"
			pdf.move_down 10
			pdf.text "Madame, Monsieur, Pour faire suite à votre passage sur notre stand à la foire de Chalons en champagne, et à notre visite du 28 septembre 2015, et selon votre demande,  veuillez trouver ci-dessous notre meilleure proposition concernant les travaux de remplacement de fenêtre de toit de marque VELUX en votre maison d’habitation sise –  30, grande rue à BREVEURY SUR COOLE (51240) - ", align: :justify

			pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
		end

		# Saut de page
		pdf.start_new_page
		
		# ON AFFICHE LES PRESTATIONS
		pdf.text "NATURE ET DESCRIPTIF DES TRAVAUX", align: :center, color: section_color
		pdf.move_down 40
		
		self.volets.each do |volet|
			volet_total = 0

			pdf.text volet.libelle, color: title_color
			pdf.move_down 20
			
			volet.prestation_lines.each do |prestation_line|
				# pdf.text ActionController::Base.helpers.strip_tags(prestation_line.description), inline_format: true, align: :justify
				pdf.text full_sanitizer.sanitize(prestation_line.description, tags: permit_tags, attributes: permit_attributes), inline_format: true, align: :justify
				pdf.move_down 2

				pdf.bounding_box([10, pdf.cursor], width: 400, height: 20) do
					pdf.text "#{prestation_line.quantite.to_s} #{prestation_line.unite } à #{prestation_line.price.to_s} € HT par #{prestation_line.unite}"
					pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
				end
				pdf.bounding_box([410, pdf.cursor+20], width: 100, height: 20) do
					pdf.text "#{prestation_line.price * prestation_line.quantite} € HT", align: :right
					pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
				end
				volet_total += prestation_line.price * prestation_line.quantite
				estimation_tva[prestation_line.tva.id] += prestation_line.price * prestation_line.quantite * prestation_line.tva.value / 100
				pdf.move_down 15
			end
			pdf.move_down 5
			# ON AFFICHE LE TOTAL
			pdf.bounding_box([10, pdf.cursor], width: 400, height: 20) do
					pdf.text "Sous-Total :", color: title_color
					pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
			end
			pdf.bounding_box([410, pdf.cursor+20], width: 100, height: 20) do
				pdf.text "#{volet_total} € HT", align: :right, color: title_color
				pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
			end

			recap << [volet.libelle, volet_total]
		end
		
		#
		# RECAPITULATIF
		#
		pdf.move_down 40
		pdf.text "RECAPITULATIF", align: :center, color: section_color
		pdf.move_down 40

		recap.each do |volet|
			pdf.bounding_box([10, pdf.cursor], width: 400, height: 20) do
				pdf.text volet[0]
				pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
			end
			pdf.bounding_box([410, pdf.cursor+20], width: 100, height: 20) do
				estimation_total_ht += volet[1]
				pdf.text "#{volet[1]} €", align: :right
				pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
			end
		end
		
		# TOTAUX
		pdf.move_down 5
		
		pdf.bounding_box([10, pdf.cursor], width: 400, height: 20) do
			pdf.text "MONTANT TOTAL HT"
			pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
		end
		pdf.bounding_box([410, pdf.cursor+20], width: 100, height: 20) do
			pdf.text "#{estimation_total_ht} €", align: :right
			pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
		end
		# TVA
		estimation_total_ttc = estimation_total_ht
		estimation_tva.each do |k, v|
			if !(v == 0)
				pdf.bounding_box([10, pdf.cursor], width: 400, height: 20) do
					pdf.text "TVA à #{Tva.find(k).name} %"
					pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE

				end
				pdf.bounding_box([410, pdf.cursor+20], width: 100, height: 20) do
					pdf.text "#{v} €", align: :right
					pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
				end
				estimation_total_ttc += v
			end
		end
		pdf.bounding_box([10, pdf.cursor], width: 400, height: 20) do
			pdf.text "MONTANT TOTAL TTC"
			pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
		end
		pdf.bounding_box([410, pdf.cursor+20], width: 100, height: 20) do
			pdf.text "#{estimation_total_ttc} €", align: :right
			pdf.transparent(0.5) {pdf.stroke_bounds} # A ENLEVER EN VERSION FINALE
		end

		#
		# CONDITION
		#
		pdf.move_down 40
		pdf.text "CONDITIONS", align: :center, color: section_color
		pdf.move_down 40

		pdf.text "A/ DE REGLEMENT"
		pdf.move_down 10

		pdf.text "B/ DE GARANTIE"
		pdf.move_down 10

		pdf.text "C/ ACCEPTATION DU PRESENT DEVIS"
		pdf.move_down 10

		pdf.text "D/ DATE D'INTERVENTION"
		pdf.move_down 10

		# GENERATION DU PDF
		pdf.render_file File.join(Rails.root, "public/pdf", "devis_#{self.id}.pdf") 
	end

end

app/models/estimation/prestation_line.rb
class Estimation::PrestationLine < ActiveRecord::Base
	belongs_to :prestation,  required: true
	delegate :price, :description, :unite, :tva, to: :prestation, allow_nil: true 
	validates :quantite, presence: true
end

app/models/estimation/volet.rb
class Estimation::Volet < ActiveRecord::Base
	has_many :prestation_lines, dependent: :destroy
	accepts_nested_attributes_for :prestation_lines, allow_destroy: true
	validates :libelle, presence: true
end

app/controllers/estimations_controller.rb
class EstimationsController < BaseController
	has_scope :with_associations, default: nil, allow_blank: true, only: [:edit, :show, :generate_pdf]

	respond_to :pdf, only: :generate_pdf

	def generate_pdf
		respond_with *with_chain(resource) do |format|
			format.pdf do
	    	render pdf: "Devis_#{resource.id}",
		     	template: 'estimations/generate_pdf.pdf.slim',
		     	layout: 'layouts/application.pdf.slim',
		     	cover: '<h1>COVER</h1>',
		     	footer: {
						center: "Center",
						left: "Left",
						right: "Right"
		     	},
		     	margin: { top: 15, bottom: 15, left: 20, right: 20 },
		     	show_as_html: params[:debug].present?,
		     	save_to_file: Rails.root.join('public/pdf', "Devis_#{resource.id}.pdf")
		  end
	  end
	end

	def send_pdf
		object = resource
		EstimationMailer.send_to_customer(object).deliver_now
		respond_to do |format|
			if true
				format.html { redirect_to(object, notice: 'Devis correctement envoyé.') }
			else
				format.html { redirect_to(object, notice: 'Erreur en envoi de mail.') }
			end
		end
	end

end

app/helpers/estimation_helper.rb
module EstimationHelper
  def h_prestation_line(libelle, price, currency)
  	content_tag :div, class: 'prestation_line' do 
      concat content_tag(:div, libelle, class: 'libelle')
      concat content_tag(:div, price, class: 'price')
      concat content_tag(:div, currency, class: 'currency')
  	end
  end
  def h_title(title)
  	content_tag :div, title, class: 'text-center title'
  end
end

app/views/estimations/_estimation_body.html.slim
.estimation-main

	- recap = []
	- estimation_total_ht, estimation_total_ttc = 0
	- estimation_tva = {}
	-	Tva.all.each{|t| estimation_tva[t.id] = 0}

	//
	// NATURE ET DESCRIPTIF DES TRAVAUX
	//

	= h_title 'NATURE ET DESCRIPTIF DES TRAVAUX'

	- resource.volets.each do |volet|

		- volet_total = 0

		.volet_libelle
			= volet.libelle
		
		- volet.prestation_lines.each_with_index do |prestation_line, i|
			.no-break.prestation
				= raw(prestation_line.description.gsub(/<div[^<]*>/, '\0' + "#{(i+1).to_s} - "))
				= h_prestation_line "#{prestation_line.quantite} #{prestation_line.unite} à #{prestation_line.price} € HT par #{prestation_line.unite}", (prestation_line.price * prestation_line.quantite), '€ HT'
			
			- volet_total += prestation_line.price * prestation_line.quantite
			- estimation_tva[prestation_line.tva.id] += prestation_line.price * prestation_line.quantite * prestation_line.tva.value / 100
			
		.volet_total
			= h_prestation_line 'Sous-Total', volet_total, '€ HT'
		

		- estimation_total_ht += volet_total
		- recap << [volet.libelle, volet_total]

	//
	// RECAPITULATIF
	//
	.no-break
		= h_title 'RECAPITULATIF'

		- recap.each do |volet|
			= h_prestation_line volet[0], volet[1], '€ HT'
		= h_prestation_line 'MONTANT TOTAL HT', estimation_total_ht, '€ HT'

		- estimation_total_ttc = estimation_total_ht
		- estimation_tva.each do |k, v|
			- if !(v == 0)
				= h_prestation_line "TVA à #{Tva.find(k).name} %", v, '€'
			- estimation_total_ttc += v

		= h_prestation_line 'MONTANT TOTAL TTC', estimation_total_ttc, '€ HT'

	//
	// CONDITION
	//
	= h_title 'CONDITIONS'

	.no-break
		' A/ DE REGLEMENT
		ul
			li
				' Acompte commande : 30%
			li
				' Le solde fin de travaux

	.no-break.text-justify
		' B/ DE GARANTIE
		= raw(resource.guaranty.description)

	.no-break.text-justify
		' C/ ACCEPTATION DU PRESENT DEVIS
		ul
			li
				' Le prix mentionné ci-dessus est sous réserve de l'état réel du dit ouvrage constaté lors de la mise en oeuvre des travaux et du démontage de l'existant.
			/ li= "Le prix indiqué est valable jusqu’au #{resource.validity_date.strftime('%d %B %Y')}."
			li= "Le prix indiqué est valable jusqu’au #{l resource.validity_date}."

	.no-break.text-justify
		' D/ DATE d'INTERVENTION :
		br
		= resource.intervention_dates + "."
		br
		' Dans le cadre d'un accord, nous vous remercions de nous retourner le double de ce devis annoté de la mention "Devis reçu avant exécution des travaux, Bon pour accord", précisant le mode de règlement, mentionnant le lieu et date de signature, accompagné de l’attestation “Age de la propriété” vous permettant de bénéficier du taux réduit de TVA dûment complétée.
		br
		' Recevez, Madame, Monsieur, l'expression de nos sentiments distingués.

	//
	// ACCORD SUR DEVIS
	//

	.page-break
	
	= h_title "ACCORD SUR DEVIS REFERENCE #{resource.reference}"

	.row
		.small-5.columns.large-offset-7
			' YYYYY'

app/views/estimations/_form.html.slim
= simple_form_for resource, wrapper: :min_inline_foundation  do |f|
	= f.error_notification
	.callout
		.row
			.small-12.medium-5.column
				h5= "Données générales"
				.callout
					= f.input :libelle
					= f.association :customer
					= f.input :reference
					= f.input :objet
					= f.input :validity_date, as: :fdatepicker
					= f.input :intervention_dates
					= f.association :guaranty

			.small-12.medium-7.column
				.row
					.column.shrink
						h5= I18n.t(:volets, default: "Volets")
					.column
						= f.link_to_add :volets, partial: 'estimations/volet_fields', target: "#volets" do
							i.step.fi-plus.plus-icon
				hr.without-top-margin 
				#volets
					= f.fields_for :volets do |volet|
						= render 'volet_fields', f: volet

	= f.button :submit, class:'button small'
	= link_to I18n.t(:index), collection_path, class: 'button small secondary'

javascript:
  $('input.fdatepicker').fdatepicker({
  	format: 'dd/mm/yyyy',
  	language: 'fr'
	});

app/views/estimations/_prestation_line_fields.html.slim
.fields
	.row
		.column
			= f.association :prestation, label: false, wrapper: :foundation
		.small-3.medium-3.large-2.column
			= f.input :quantite, as: :integer, label: false, wrapper: :foundation
		.shrink.column
			= f.link_to_remove "", class:'postfix' do
				i.step.fi-minus-circle.minus-icon

app/views/estimations/_volet_fields.html.slim
.fields
	.row
		.columns
			= f.input :libelle, label: false, wrapper: :foundation
		.shrink.columns
			= f.link_to_remove "", class:'postfix' do
				i.step.fi-minus-circle.minus-alert-icon
	#prestations-target.panel
		= f.fields_for :prestation_lines do |prestation_line|
			= render 'prestation_line_fields', f: prestation_line
		= f.link_to_add :prestation_lines, t(:add_prestation), partial: 'estimations/prestation_line_fields', class: 'button tiny secondary'
	hr

	

app/views/estimations/generate_pdf.pdf.slim
= render partial: 'estimation_body', formats: [:html]

app/views/estimations/show.html.slim
.callout
	= simple_tag('Client', resource.customer.name)
	= simple_tag('Référence', resource.reference)
	= simple_tag('Objet', resource.objet)
	= simple_tag 'Devis' do 
		= render partial: 'estimation_body'
= link_to I18n.t(:pdf), generate_pdf_estimation_path(resource, format: :pdf), class: "button small right", target: '_blank'
= link_to :send_pdf, send_pdf_estimation_path(resource), class: "button small right"
= link_to I18n.t(:edit), edit_resource_path(resource.id), class: 'button small'
= link_to I18n.t(:index), collection_path, class: 'button small secondary'