config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]

  match 'add_nested_fields' => 'nested_form#add_nested_fields', via: :get
  root 'application#index'
  resources :customers
  resources :prestations
  resources :tvas
  resources :guaranties
  resources :estimations do 
    member do
      get 'generate_pdf'
      get 'send_pdf'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController <  ActionController::Base
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authenticate_user!
  protect_from_forgery with: :exception

  def index
  	render text: "Welcome to Bat Conseil Application", layout: 'application'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_tag(label=nil, data=nil, *args, &block)
  	options = args.extract_options!.symbolize_keys
  	content_tag :div, class: 'group-form' do 
  		concat content_tag(:span, (label + ' :'), class: 'small-12 medium-2 columns') if !label.nil?
  		concat content_tag(:span, data, class: 'small-12 medium-10 columns like-input', &block)
  	end
  end

  def simple_min_tag(label=nil, data=nil, *args, &block)
    options = args.extract_options!.symbolize_keys
    content_tag :div, class: 'group-form' do 
      concat content_tag(:span, (label + ' :'), class: 'small-12 medium-12 large-3 columns') if !label.nil?
      concat content_tag(:span, data, class: 'small-12 medium-12 large-9 columns like-input', &block)
    end
  end
end

app/views/application/_datatable_toolbar.html.slim
= link_to t(:new), new_resource_path, class: "button small float-right"

app/views/application/_flash.html.slim
- flash.each do |name, msg|
	.callout class="#{name == :notice ? "success" : "alert"}"  data-closable=""
		p= msg if msg.is_a?(String)
		button.close-button aria-label="Close alert" type="button" data-close=""
			span aria-hidden="true"
				'&times;

app/views/application/_header.html.slim
.title-bar data-responsive-toggle="menu" data-hide-for="medium"
  button.menu-icon type="button" data-toggle=""
  .title-bar-title
    ' Menu

#menu.top-bar
  .top-bar-left
    ul.menu.dropdown data-dropdown-menu=""
      li.menu-text= 'Bat Conseil'
      / li= link_to "Bat Conseil", root_path, class: 'navbar-brand'
      li= link_to I18n.t(:customers, default: "Clients"), customers_path
      li= link_to I18n.t(:prestations, default: "Prestations"), prestations_path
      li= link_to I18n.t(:devis, default: "Devis"), estimations_path
      li.hide-for-small-only
        a href="#"
          =I18n.t(:parametrage, default: "Paramétrage")
        ul.menu
          li= link_to I18n.t(:tvas, default: "Tva"), tvas_path
          li= link_to I18n.t(:guaranties, default: "Type de garantie"), guaranties_path
  .top-bar-right
    ul.menu
      - if current_user
        li= link_to I18n.t(:logout, default: "Logout"), destroy_user_session_path, method: :delete

app/views/application/edit.html.slim
= render 'form'

app/views/application/index.html.slim
.callout
	table.display.hover.responsive.nowrap id="#{controller_name}" cellspacing="0" width="100%"

javascript:
	var table = $('##{controller_name}').dataTable(#{@datatable_set.to_json.html_safe});
	$("div.toolbar").html("#{j (render partial: 'datatable_toolbar')}");

app/views/application/new.html.slim
= render 'form'